### ISSUE TITLE
Timestamp parsing error

### ISSUE THREAD

**Issue by rfetherston** [philres/catfishq#17]
Catfishq returns a timestamp parsing error when using `--print-start-time` command on FASTQ files generated by Guppy version “5.0.16+b9fcd7b”, likely due to a change in the timestamp format.

Python 3.8, catfishq 1.1.5, pysam 0.17.0
```
catfishq --print-start-time -r fastq_pass/
Traceback (most recent call last):
  File "/miniconda3/bin/catfishq", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/lib/python3.8/site-packages/catfishq/cat_fastq.py", line 351, in main
    min_start_time=get_start_time(args.FASTQ,args.RECURSIVE)
  File "/miniconda3/lib/python3.8/site-packages/catfishq/cat_fastq.py", line 264, in get_start_time
    min_start_time=compare_start_time(entry.comment,min_start_time)
  File "/miniconda3/lib/python3.8/site-packages/catfishq/cat_fastq.py", line 206, in compare_start_time
    start_time = datetime.strptime(start_time_str,'%Y-%m-%dT%H:%M:%SZ')
  File "/miniconda3/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/miniconda3/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-10-19T04:24:16.235874+01:00' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by philres** [comment]
```
try:
    start_time = datetime.strptime(start_time_str,'%Y-%m-%dT%H:%M:%SZ')
except ValueError:
    start_time = datetime.strptime(start_time_str,'%Y-%m-%dT%H:%M:%S.%f%z')
```
Think this should fix it and work with both old and new guppy version.

Could you change your version to this please and submit a pull request?
